version: '3.4'

services:
  commandapi:
    image: ${DOCKER_REGISTRY-}commandapi
    build:
      context: .
      dockerfile: CommandAPI/Dockerfile
    container_name: CommandsAPI
    ports:
      - "5226:80" 
    depends_on: 
      - postgres_db
    

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    ports:
        - "5436:5432"
    volumes:
      - ./postgres_db-data:/var/lib/postgresql/data/
    container_name: CommandsAPI-Database-Pos